"use client";

import Photo from "@/components/execucoes/Photo";
import { Input } from "postcss";
import { ChangeEvent, ChangeEventHandler, useState } from "react";

type photoData = {
	src: string;
	alt: string;
	subtitle: string;
	title: string;
};

let delay = 0;
const mainPhotoArray: photoData[] = new Array(4).fill({
	src: "https://static01.nyt.com/images/2022/09/01/business/00roose-1/merlin_212276709_3104aef5-3dc4-4288-bb44-9e5624db0b37-superJumbo.jpg",
	alt: "photo generated by ia",
	subtitle: "MidJourney",
	title: "Photo generated by ia",
});

const photoArray: photoData[] = new Array(6).fill({
	src: "https://static01.nyt.com/images/2022/09/01/business/00roose-1/merlin_212276709_3104aef5-3dc4-4288-bb44-9e5624db0b37-superJumbo.jpg",
	alt: "photo generated by ia",
	subtitle: "MidJourney",
	title: "Photo generated by ia",
});
export default function Home() {
	const [results, setResults] = useState<photoData[] | null>(null);
	const [inputValue, setInputValue] = useState<string>("");

	function handleInput(e: ChangeEvent<HTMLInputElement>) {
		const value = e.target.value;
		setInputValue(value);

		if (value !== "") {
			filterResults(value);
		} else {
			setResults(null);
		}
	}

	console.log(results);

	function filterResults(value: string) {
		const filteredResults = photoArray.filter(
			(photo) =>
				photo.title.toLowerCase().includes(value.toLowerCase()) ||
				photo.subtitle.toLowerCase().includes(value.toLowerCase())
		);
		setResults(filteredResults);
	}

	return (
		<>
			<main className="sm:gap-5 md:px-[10%] lg:px-[15%] px-4 mb-20 text-gray-400">
				<div className="border-b-[1px] flex justify-start mx-auto md:w-3/5 w-fu mb-10 items-baseline border-gray-700">
					<i className="bi bi-search text-xl text-white"></i>
					<input
						value={inputValue}
						onChange={handleInput}
						className="bg-transparent px-5 py-4 focus:outline-none text-xs w-full"
						placeholder="Procure por trabalhos ou clientes "
					/>
				</div>

				{inputValue !== "" ? (
					<div className="grid place-items-center md:grid-cols-3 grid-cols-1 mt-4 md:mt-16 justify-center  lg:justify-between gap-2 sm:gap-7">
						{results?.map((photo, index) => {
							return (
								<Photo
									id={index + 1}
									delay={index > 0 ? delay : 0}
									key={index}
									src={photo.src}
									alt={photo.alt}
									subtitle={photo.subtitle}
									title={photo.title}
									dark={true}
								/>
							);
						})}
					</div>
				) : (
					<div className="grid gap-2 sm:gap-7 md:grid-cols-2 grid-cols-1 justify-center lg:justify-between ">
						{mainPhotoArray.map((photo, index) => {
							delay += 0.15;

							switch (index) {
								case 0:
								case 3:
								case 6:
								case 9:
									delay = 0;
							}

							return (
								<Photo
									delay={index > 0 ? delay : 0}
									key={index}
									src={photo.src}
									alt={photo.alt}
									subtitle={photo.subtitle}
									title={photo.title}
									id={index + 1}
									dark={true}
								/>
							);
						})}{" "}
					</div>
				)}

				<div className="grid place-items-center md:grid-cols-3 grid-cols-1 mt-4 md:mt-16 justify-center  lg:justify-between gap-2 sm:gap-7">
					{inputValue == ""
						? photoArray.map((photo, index) => {
								delay += 0.15;

								switch (index) {
									case 0:
									case 3:
									case 6:
									case 9:
										delay = 0;
								}

								return (
									<Photo
										id={index + 1}
										delay={index > 0 ? delay : 0}
										key={index}
										src={photo.src}
										alt={photo.alt}
										subtitle={photo.subtitle}
										title={photo.title}
										dark={true}
									/>
								);
						  })
						: undefined}
				</div>
			</main>
		</>
	);
}
