"use client";

import Image from "next/image";
import header_image from "./assets/image/header-image.jpg";
import { motion } from "framer-motion";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Photo from "@/components/home/Photo";
import PhotoReveal from "@/components/PhotoReveal";

type photoData = {
	src: string;
	alt: string;
	subtitle: string;
	title: string;
};

let delay = 0;

export default function Home() {
	const photoArray: photoData[] = new Array(12).fill({
		src: "https://static01.nyt.com/images/2022/09/01/business/00roose-1/merlin_212276709_3104aef5-3dc4-4288-bb44-9e5624db0b37-superJumbo.jpg",
		alt: "photo generated by ia",
		subtitle: "MidJourney",
		title: "Photo generated by ia",
	});
	return (
		<>
			<Header />
			<PhotoReveal src="./assets/image/header-image.jpg" />
			<main className="lg:px-80 md:px-20 px-7 mb-20">
				<div className="flex mt-16 flex-wrap justify-center  lg:justify-between gap-4 gap-x-2">
					{photoArray.map((photo, index) => {
						let width = 300;

						delay += 0.15;

						switch (index) {
							case 0:
							case 3:
							case 6:
							case 9:
								delay = 0;
						}

						switch (index + 1) {
							case 1:
							case 6:
							case 7:
							case 12:
								width = 620;
								break;

							default:
								break;
						}

						return (
							<Photo
								delay={index > 0 ? delay : 0}
								key={index}
								width={width}
								src={photo.src}
								alt={photo.alt}
								subtitle={photo.subtitle}
								title={photo.title}
							/>
						);
					})}
				</div>
			</main>
			<Footer />
		</>
	);
}
