"use client";

import Image from "next/image";
import header_image from "./assets/image/header-image.jpg";
import { motion } from "framer-motion";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Photo from "@/components/home/Photo";

type photoData = {
	src: string;
	alt: string;
	subtitle: string;
	title: string;
};

export default function Home() {
	const photoArray: photoData[] = new Array(12).fill({
		src: "https://static01.nyt.com/images/2022/09/01/business/00roose-1/merlin_212276709_3104aef5-3dc4-4288-bb44-9e5624db0b37-superJumbo.jpg",
		alt: "photo generated by ia",
		subtitle: "MidJourney",
		title: "Photo generated by ia",
	});
	return (
		<>
			<Header />
			<header className="lg:mx-32  relative md:mb-20 mt-40 mb-10 z-50 max-w-fit max-h-[700px] overflow-hidden">
				<motion.img
					animate={{ scaleX: 1, opacity: 1 }}
					initial={{ scaleX: 0.5, opacity: 0 }}
					transition={{ duration: 1 }}
					whileHover={{ scale: 1.1 }}
					className="cursor-pointer opacity-90 object-cover max-h- w-full"
					src="/assets/image/header-image.jpg"
				/>
				<motion.h1
					animate={{ y: 0, opacity: 1 }}
					initial={{ y: 100, opacity: 0 }}
					transition={{ duration: 1, delay: 0.5 }}
					className="absolute font-instrument_serif sm:text-4xl text-2xl top-[45%] left-12 sm:left-1/4  z-10 text-white"
				>
					We&apos;ve come a long, long way <br /> together
				</motion.h1>
			</header>
			<main className="lg:px-80 md:px-20 px-7 mb-20">
				<div className="flex flex-wrap justify-center  lg:justify-between gap-4 gap-x-2">
					{photoArray.map((photo, index) => {
						let width = 300;

						switch (index + 1) {
							case 1:
							case 6:
							case 7:
							case 12:
								width = 620;
								break;

							default:
								break;
						}

						return (
							<Photo
								key={index}
								width={width}
								src={photo.src}
								alt={photo.alt}
								subtitle={photo.subtitle}
								title={photo.title}
							/>
						);
					})}
				</div>
			</main>
			<Footer />
		</>
	);
}
