"use client";
import { useSearchParams } from "next/navigation";
import Photo from "@/components/execucoes/Photo";
import PhotoReveal from "@/components/PhotoReveal";
import MainPicReveal from "@/components/MainPicReveal";

type photoData = {
	src: string;
	alt: string;
	subtitle: string;
	title: string;
};

let delay = 0;

export default function Home() {
	const mainPhotoArray: photoData[] = new Array(3).fill({
		src: "https://static01.nyt.com/images/2022/09/01/business/00roose-1/merlin_212276709_3104aef5-3dc4-4288-bb44-9e5624db0b37-superJumbo.jpg",
		alt: "photo generated by ia",
		subtitle: "MidJourney",
		title: "Photo generated by ia",
	});

	const photoArray: photoData[] = new Array(6).fill({
		src: "https://static01.nyt.com/images/2022/09/01/business/00roose-1/merlin_212276709_3104aef5-3dc4-4288-bb44-9e5624db0b37-superJumbo.jpg",
		alt: "photo generated by ia",
		subtitle: "MidJourney",
		title: "Photo generated by ia",
	});
	return (
		<>
			<div>
				<MainPicReveal conceito={false} src={process.env.NEXT_PUBLIC_VIDEOURL} />
			</div>
			<main className="sm:gap-5 lg:px-headerPaddingLG md:px-headerPadding px-4 -mb-5 md:-mb-0 mt-10">
				<div className="flex flex-col md:flex-row  flex-nowrap gap-2 sm:gap-5 lg:gap-7">
					{mainPhotoArray.map((photo, index) => {
						delay += 0.15;
						let size = "w-full";
						switch (index) {
							case 0:
								delay = 0;
						}

						switch (index) {
							case 0:
								size = "md:w-[50%]";
								break;
							case 1:
							case 2:
								size = "md:w-[25%]";
						}

						return (
							<Photo
								delay={index > 0 ? delay : 0}
								key={index}
								src={photo.src}
								alt={photo.alt}
								subtitle={photo.subtitle}
								title={photo.title}
								id={index + 1}
								size={size}
								main={true}
							/>
						);
					})}
				</div>
				<div className="flex flex-col md:flex-row flex-nowrap gap-2 sm:gap-5 lg:gap-7">
					{mainPhotoArray.map((photo, index) => {
						delay += 0.15;
						let size2 = "w-full";
						switch (index) {
							case 0:
								delay = 0;
						}

						switch (index) {
							case 2:
								size2 = "md:w-[50%]";
								break;
							case 0:
							case 1:
								size2 = "md:w-[23%]";
						}

						return (
							<Photo
								delay={index > 0 ? delay : 0}
								key={index}
								src={photo.src}
								alt={photo.alt}
								subtitle={photo.subtitle}
								title={photo.title}
								id={index + 1}
								size={size2}
								main={true}
							/>
						);
					})}
				</div>
				<div className="grid place-items-center md:grid-cols-3 grid-cols-1 mt-4 md:mt-16 justify-center  lg:justify-between gap-2 sm:gap-5 lg:gap-7">
					{photoArray.map((photo, index) => {
						delay += 0.15;

						switch (index) {
							case 0:
							case 3:
							case 6:
							case 9:
								delay = 0;
						}

						return (
							<Photo
								id={index + 1}
								delay={index > 0 ? delay : 0}
								key={index}
								src={photo.src}
								alt={photo.alt}
								subtitle={photo.subtitle}
								title={photo.title}
							/>
						);
					})}
				</div>
			</main>
		</>
	);
}
